### ISSUE TITLE
why trade model do not start?

### ISSUE THREAD

**Issue by ideaplat** [taurusai/kungfu#1]
![image](https://user-images.githubusercontent.com/2016679/32874098-031531fa-cacb-11e7-8801-074d5743cf6f.png)

**Comment by taurusai** [comment]
most likely because your kungfu.json setting. would you please show your error log in /shared/kungfu/log/trade_engine.log?

**Comment by ideaplat** [comment]
17-11-15 22:52:27.926 INFO  TradeEngine.CTP %% - [ATTENTION] default to confirm settlement and no authentication!
17-11-15 22:52:27.930 INFO  TradeEngine.CTP %% - IEngine::init FrontUri->"tcp://180.168.146.187:10000"
17-11-15 22:52:27.930 INFO  TradeEngine.CTP %% - IEngine::init NeedAuth->false
17-11-15 22:52:27.930 INFO  TradeEngine.CTP %% - IEngine::init NeedSettleConfirm->true
17-11-15 22:52:27.930 INFO  TradeEngine.CTP %% - IEngine::init accounts->[{"clients":["YOUR_STRATEGY1","YOUR_STRATEGY2","YOUR_STRATEGY3"],"info":{"BrokerId":"9999","InvestorId":"106943","Password":"234567","UserId":"105943"},"is_default":true}]
17-11-15 22:52:27.930 INFO  TradeEngine.CTP %% - [account] number: 1
17-11-15 22:52:27.930 INFO  TradeEngine.CTP %% - [client] (name)YOUR_STRATEGY1 (account)106943
17-11-15 22:52:27.930 INFO  TradeEngine.CTP %% - [client] (name)YOUR_STRATEGY2 (account)106943
17-11-15 22:52:27.930 INFO  TradeEngine.CTP %% - [client] (name)YOUR_STRATEGY3 (account)106943
17-11-15 22:52:27.952 INFO  TradeEngine.CTP %% - [OnFrontConnected] (idx)0
17-11-15 22:52:27.992 ERROR TradeEngine.CTP %% - [OnRspUserLogin] (errId)3 (errMsg)CTP:~M~P~H~U~Z~D~Y»~U
17-11-15 22:54:07.207 INFO  TradeEngine.CTP %% - [ATTENTION] default to confirm settlement and no authentication!
17-11-15 22:54:07.211 INFO  TradeEngine.CTP %% - IEngine::init FrontUri->"tcp://180.168.146.187:10000"
17-11-15 22:54:07.211 INFO  TradeEngine.CTP %% - IEngine::init NeedAuth->false
17-11-15 22:54:07.211 INFO  TradeEngine.CTP %% - IEngine::init NeedSettleConfirm->true
17-11-15 22:54:07.211 INFO  TradeEngine.CTP %% - IEngine::init accounts->[{"clients":["YOUR_STRATEGY1","YOUR_STRATEGY2","YOUR_STRATEGY3"],"info":{"BrokerId":"9999","InvestorId":"106943","Password":"234567","UserId":"105943"},"is_default":true}]
17-11-15 22:54:07.211 INFO  TradeEngine.CTP %% - [account] number: 1
17-11-15 22:54:07.211 INFO  TradeEngine.CTP %% - [client] (name)YOUR_STRATEGY1 (account)106943
17-11-15 22:54:07.211 INFO  TradeEngine.CTP %% - [client] (name)YOUR_STRATEGY2 (account)106943
17-11-15 22:54:07.211 INFO  TradeEngine.CTP %% - [client] (name)YOUR_STRATEGY3 (account)106943
17-11-15 22:54:07.253 INFO  TradeEngine.CTP %% - [OnFrontConnected] (idx)0
17-11-15 22:54:07.280 ERROR TradeEngine.CTP %% - [OnRspUserLogin] (errId)3 (errMsg)CTP:~M~P~H~U~Z~D~Y»~U
17-11-15 22:55:12.636 INFO  TradeEngine.CTP %% - [ATTENTION] default to confirm settlement and no authentication!
17-11-15 22:55:12.639 INFO  TradeEngine.CTP %% - IEngine::init FrontUri->"tcp://180.168.146.187:10000"
17-11-15 22:55:12.639 INFO  TradeEngine.CTP %% - IEngine::init NeedAuth->false
17-11-15 22:55:12.639 INFO  TradeEngine.CTP %% - IEngine::init NeedSettleConfirm->true
17-11-15 22:55:12.639 INFO  TradeEngine.CTP %% - IEngine::init accounts->[{"clients":["YOUR_STRATEGY1","YOUR_STRATEGY2","YOUR_STRATEGY3"],"info":{"BrokerId":"9999","InvestorId":"106943","Password":"234567","UserId":"ideaplat"},"is_default":true}]
17-11-15 22:55:12.639 INFO  TradeEngine.CTP %% - [account] number: 1



and I know I modified the configuration file，and I well down.

Thank you .

td_ctp: started
kungfu> status
md_ctp                           RUNNING   pid 1316, uptime 22:58:11
td_ctp                           RUNNING   pid 2560, uptime 0:00:15
yijinjing                        RUNNING   pid 1284, uptime 23:18:13

**Comment by sunsiyue** [comment]
@ghost hey buddy, what broker did you connect to?
