### ISSUE TITLE
可以公开dockerfile吗

### ISSUE THREAD

**Issue by orzyx** [taurusai/kungfu#16]

**Comment by lijifeng007** [comment]
dockerfile一般跟应用绑定会蛮紧密的。比如说：从自己的私有repo获取构建好的artifact。从目前来看：自己做的话，可以根据官方centos镜像，下载kungfu的rpm，然后把systemd相关配置设置（kungfu开源了这些配置文件）下，应该就可以了。

**Comment by taurusai** [comment]
2.0 不再需要docker。
