### ISSUE TITLE
kungfu image在阿里容器云上不能部署等问题

### ISSUE THREAD

**Issue by lijifeng007** [taurusai/kungfu#17]
描述：
kongfu 容器启动的时候，会加入privileged参数，但是在阿里容器云上，并不支持该参数。
问题：
1.  对于上述参数不支持的问题，站在云提供商的角度，容器对宿主机不能有过多的侵入。不知道kungfu有什么好建议？
2.  目前业界通用的做法，一个容器一个进程。但是从目前来看，kungfu是把容器当做虚拟机来使用，里面启用了好几个应用。想请问下，实际生产部署，容器是否可行？

**Comment by orzyx** [comment]
开发参与者文档尽快公布比较好

**Comment by dongkeren** [comment]
@lijifeng007 问题1我们正在解决，之前是因为功夫依赖的systemd必需要有这个参数才能正常运行，最近有人已经解决了这个问题（详见：https://developers.redhat.com/blog/2016/09/13/running-systemd-in-a-non-privileged-container/）我们会尽快跟进。
问题2，由于功夫依赖一系列服务，如果坚持一容器一进程原则，会极大的增加部署和运维难度，考虑到功夫的核心功能是支持交易，一般会部署在独立可控的环境下，而非典型互联网应用的部署方式，功夫集成式的做法实际上就是目前背景下的best practise。
