### ISSUE TITLE
why cpu is 100%?

### ISSUE THREAD

**Issue by ideaplat** [taurusai/kungfu#2]
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
26355 666       20   0  797620  26788  16796 S 100.7  0.7   5:32.65 wingchun
 8814 666       20   0 1501884  23720  15396 S 100.3  0.6   1406:29 yjj
 8955 666       20   0  597716  33260  24120 S 100.0  0.8   1395:33 wingchun
    1 root      20   0  137236   4820   3368 S   0.0  0.1   0:10.04 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.04 kthreadd     

I enter the command：Top，but cpu  is 100%,why?
how to modify ? it is very power

**Comment by taurusai** [comment]
Kungfu is latency-oriented by design, we use full CPU to ensure you have the lowest system latency. Right now there is no way to change that, we will consider to add a power-saving mode in future.
