### ISSUE TITLE
请问make package时出现cannot copy file的问题怎么解决？

### ISSUE THREAD

**Issue by qinyuLT** [taurusai/kungfu#29]
CMake Error at /kungfu/build/cmake_install.cmake:36 (file):
  file INSTALL cannot copy file
  "/kungfu/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/longfist/api/xtp/XTP_API_20171115_1.1.16.9/doc/XTP
  QuoteAPI使用UDP常见问题.doc" to
  "/kungfu/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/build/_CPack_Packages/Linux/RPM/kungfu-0.0.5-Linux/opt/kungfu/master/lib/longfist/api/xtp/XTP_API_20171115_1.1.16.9/doc/XTP
  QuoteAPI使用UDP常见问题.doc".

CPack Error: Error when generating package: kungfu
make: *** [package] Error 1

**Comment by qinyuLT** [comment]
我在docker run的时候挂载了本地文件，命令是：
docker run -it --name kf --privileged=true --ulimit memlock=-1 -v /home/kungfu:/kungfu image.taurusai.com/library/kungfu-devel /bin/bash

**Comment by taurusai** [comment]
2.0 does not need docker anymore
