### ISSUE TITLE
项目还在更新吗？

### ISSUE THREAD

**Issue by whitelilis** [taurusai/kungfu#35]
最后一次更新是在好几个月之前了，是不是只忙着商业化去了？

**Comment by taurusai** [comment]
近期确实是的，只有公司运营好一些才有更多力量贡献开源

**Comment by williamlfang** [comment]
已经停掉好久了。。。

**Comment by newhotter** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    黄了应该
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                10512076
                            
                    
                        
                            
                                    10512076@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2018年10月15日 15:26，whitelilis<notifications@github.com> 写道： 


最后一次更新是在好几个月之前了，是不是只忙着商业化去了？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by newhotter** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        创业太难，感觉这个项目要凉凉
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                10512076
                            
                    
                        
                            
                                    10512076@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年3月13日 11:53，William Fang<notifications@github.com> 写道： 


已经停掉好久了。。。



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by taurusai** [comment]
请看2.0更新。
