### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by mercury20160104** [taurusai/kungfu#37]
kungfu的这个项目的安装配置说明写的很杂乱，一时说用docker，一时说源码编译。条理比较混乱，让人走了不少的弯路。建议理清下整个readme.md。

**Comment by mercury20160104** [comment]
[%5] Linking CXX Shared library libjournal.so
/usr/bin/ld : 找不到 -lpython
collects : 错误：ld返回1

**Comment by mercury20160104** [comment]
建立一个软连接即可

**Comment by taurusai** [comment]
2.0更新了readme，不再需要使用docker
