### ISSUE TITLE
"yum install  kungfu-0.0.2-Linux.rpm" block issue.

### ISSUE THREAD

**Issue by leochan007** [taurusai/kungfu#5]
^Cuseradd: user 'bruce' already exists
warning: %post(kungfu-0.0.2-20171123112041.x86_64) scriptlet failed, signal 2
Non-fatal POSTIN scriptlet failure in rpm package kungfu-0.0.2-20171123112041.x86_64

**Comment by leochan007** [comment]
mkdir docker in project root dir.
in docker dir, there is a docker-compose.xml 

version: '3'

services:

  kungfu-dev:
    #build:
    #  context: ./kungfu-dev
    #  dockerfile: Dockerfile
    image: taurusai/kungfu-devel
    container_name: kungfu-dev
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
    network_mode: "host"
      #app_net:
      #  ipv4_address: 192.168.170.170
    volumes:
      - ../:/local-dev
    entrypoint:
      - "/usr/sbin/init"
    privileged: true
    ulimits:
      #- nproc: 65535
      memlock: -1


networks:
  app_net:
    driver: bridge
    #external:
    #  name: app_net

to map the src in container.

**Comment by leochan007** [comment]
host: ubuntu 16.04

should the host be centos7 ? is that a MUST?

**Comment by leochan007** [comment]
i just try it on centos 7.4.1708 still hangs when yum install RPM file.

**Comment by taurusai** [comment]
@leochan007 
do you have kungfu installed on your docker already?
We have been through some unexpected script issue before, and following steps may help.
1. try to "yum erase kungfu"
2. if any failure, use "rpm -e --noscripts kungfu" to remove directly.
3. install kungfu rpm using "yum install" again.

Please let me know if not fix your problem

**Comment by leochan007** [comment]
i recreate docker container many times. everything the env is brand new.

**Comment by leochan007** [comment]
i recreate docker container many times. everytime the env is brand new.

**Comment by taurusai** [comment]
2.0 does not need docker anymore
