### ISSUE TITLE
module 'distutils' has no attribute 'distutils_path'

### ISSUE THREAD

**Issue by Hybueno09** [taurusai/kungfu#54]
yarn build 过程中，kfc-win.spec 文件中报如下错误，

`
 |     exec(code, spec_namespace) 

 |   File "python\kfc-win.spec", line 7, in <module> 

 |     if distutils.distutils_path.endswith('__init__.py'): 

 | AttributeError: module 'distutils' has no attribute 'distutils_path' 
`
python 版本 3.7.0
是 python 版本不兼容还是什么问题

**Comment by tsjumper** [comment]
您好，我也遇到了这个问题，请问您是怎么解决的？
