### ISSUE TITLE
Any plan for adding RPC/IPC support?

### ISSUE THREAD

**Issue by mysl** [taurusai/kungfu#7]
First of all,  great project, thank you so much for open sourcing it.

At the same time I have a suggestion:  why not provide some support for RPC/IPC interface?  With this approach,  users from different backtesting systems can take kungfu as an execution system/server, which is supposed to be the superior advantage of kungfu system, right?  This can detour the limit and open the door to attract much more users (potentially using different backtesting systems,  different languages other than python 2.7 and c++,  different oses othan than centos ) to join the community.

**Comment by taurusai** [comment]
We surely will add such interfaces.

**Comment by mysl** [comment]
cool, thanks for confirming
